# Generated by Django 5.1 on 2024-08-26 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Застройщик',
                'verbose_name_plural': 'Застройщики',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='Имя заказчика')),
                ('buyer_firstname', models.CharField(max_length=255, verbose_name='Фамилия заказчика')),
                ('comment', models.CharField(blank=True, null=True, verbose_name='Комментарий')),
                ('building_time_start', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала строительства')),
                ('building_time_finish', models.DateTimeField(verbose_name='Дата окончания строительства')),
                ('key_time', models.DateTimeField(verbose_name='Дата выдачи ключей')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес работы')),
                ('is_exists', models.BooleanField(default=True, verbose_name='Возможность взаимодействия')),
            ],
            options={
                'verbose_name': 'Риэлтор',
                'verbose_name_plural': 'Риэлторы',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название услуги для дома')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_development', models.DateTimeField(verbose_name='Дата постройки')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house_shop.developer', verbose_name='Застройщик')),
            ],
            options={
                'verbose_name': 'Застройка',
                'verbose_name_plural': 'Застройки',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('size', models.CharField(max_length=255, verbose_name='Размер')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Изображение')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания объявления')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления объявления')),
                ('is_exists', models.BooleanField(default=True, verbose_name='Доступность к заказу')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house_shop.developer', verbose_name='Застройщик')),
                ('service', models.ManyToManyField(blank=True, null=True, to='house_shop.services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
        migrations.CreateModel(
            name='PosDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house_shop.development', verbose_name='Застройка')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house_shop.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Позиция застройки',
                'verbose_name_plural': 'Позиции застроек',
            },
        ),
        migrations.AddField(
            model_name='development',
            name='house',
            field=models.ManyToManyField(through='house_shop.PosDevelopment', to='house_shop.house', verbose_name='Дом'),
        ),
        migrations.CreateModel(
            name='PosOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house_shop.house', verbose_name='Дом')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house_shop.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='house',
            field=models.ManyToManyField(through='house_shop.PosOrder', to='house_shop.house', verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='order',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='house_shop.realtor', verbose_name='Риэлтор'),
        ),
    ]
